services:
    fastapi:
        build:
          context: ./fastapi
        environment:
          - PORT=${PORT}
        ports:
            - "${PORT}:${TROP}"
        volumes:
            - ./fastapi:/app
        depends_on:
          - db
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PASS}
            POSTGRES_DB: beforeitsprinted
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: