services:
  bipdb:
    image: postgres:16
    container_name: bipdb
    env_file: [.env]
    expose: [5432]
    volumes: [postgres_data:/var/lib/postgresql/data]
    restart: unless-stopped
#    networks: [gabibdods]

  bipfa:
    stop_grace_period: 1s
    build: ./parser
    container_name: bipfa
    ports: [9000]
    depends_on: [bipdb]
    restart: unless-stopped
#    networks: [gabibdods]

  bippx:
    stop_grace_period: 1s
    build: ./proxy
    container_name: bippx
    env_file: [.env]
    expose: [3000]
    depends_on: [bipfa]
    restart: unless-stopped
#    networks: [gabibdods]

  bipcf:
    image: cloudflare/cloudflared:latest
    container_name: hgcf
    env_file: [.env]
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on: [bippx]
    restart: unless-stopped
#    networks: [gabibdods]

volumes:
  postgres_data:

#networks:
#  gabibdods:
#    external: true
