services:
    fastapi:
        build: ./fastapi
        ports:
            - "${PORT}:8081"
        volumes:
            - ./fastapi:/app
        depends_on:
          - db
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: bip
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: