services:
  bipdb:
    image: postgres:16
    container_name: bipdb
    env_file: [.env]
    expose: [5432]
    volumes: [postgres_data:/var/lib/postgresql/data]
    restart: unless-stopped
    networks: [gabibdods]

  bipfa:
    build: ./parser
    container_name: bipfa
    ports: [9000:9000]
    depends_on: [bipdb]
    restart: unless-stopped
    networks: [gabibdods]

  bippx:
    build: ./proxy
    container_name: bippx
    env_file: [.env]
    ports: [3000:3000]
    depends_on: [bipfa]
    restart: unless-stopped
    networks: [gabibdods]

volumes:
  postgres_data:

networks:
  gabibdods:
    external: true
