name: beforeitsprinted

on:
  push:
    tags:
    - BIP
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        env:
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
          TF_VAR_postgres_pass: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_app_dir: ${{ secrets.APP_DIR }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_trop: ${{ secrets.TROP }}
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
          TF_VAR_postgres_pass: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_app_dir: ${{ secrets.APP_DIR }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_trop: ${{ secrets.TROP }}
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: terraform apply -auto-approve

      - name: Terraform Output
        if: failure()
        env:
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
          TF_VAR_postgres_pass: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_app_dir: ${{ secrets.APP_DIR }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_trop: ${{ secrets.TROP }}
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: terraform output

      - name: Failsafe - show terraform.log
        if: failure()
        run: cat terraform.log

      - name: Print Terraform Log
        if: failure()
        run: cat terraform.log

      - name: Terraform Validate
        run: terraform validate