name: beforeitsprinted

on:
    push:
        tags:
          - BIP
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            TF_VAR_dir: ${{ secrets.DIR }}
            TF_VAR_user: ${{ secrets.USER }}
            TF_LOG: DEBUG
            TF_LOG_PATH: terraform.log
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Set Up Terraform
            uses: hashicorp/setup-terraform@v2

          - name: Terraform Init
            run: terraform init

          - name: Terraform Validate
            run: terraform validate

          - name: Terraform Plan
            run: terraform plan

          - name: Terraform Apply
            run: terraform apply -auto-approve

          - name: Terraform Output
            if: failure()
            run: terraform output

          - name: Print Terraform Log
            if: failure()
            run: cat terraform.log