name: beforeitsprinted

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, Windows]
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check SSH Availability
        run: ssh -V

      - name: Taint Previous Terraform Provisioner
        uses: terraform taint null_resource.deploy_compose

      - name: Destroy Previous Terraform Provisioner
        uses: terraform destroy -target=null_resource.deploy_compose

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_postgres_pass: ${{ secrets.POSTGRES_USER }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_app_dir: ${{ secrets.APP_DIR }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_trop: ${{ secrets.TROP }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_postgres_pass: ${{ secrets.POSTGRES_USER }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_app_dir: ${{ secrets.APP_DIR }}
          TF_VAR_port: ${{ secrets.PORT }}
          TF_VAR_trop: ${{ secrets.TROP }}

      - name: Terraform Validate
        run: terraform validate