name: beforeitsprinted

on:
    push:
        tags:
          - BIP
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted
        env:
            TF_VAR_dir: ${{ secrets.DIR }}
            TF_VAR_user: ${{ secrets.USER }}
            PORT:  ${{ secrets.PORT }}
            TROP:  ${{ secrets.TROP }}
            PSQL_USER: ${{ secrets.PSQL_USER }}
            PSQL_PASS: ${{ secrets.PSQL_PASS }}
            PYTHONDONTWRITEBYTECODE: "1"

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Set Up Terraform
            uses: hashicorp/setup-terraform@v2

          - name: Terraform Init
            run: terraform init

          - name: Terraform Validate
            run: terraform validate

          - name: Terraform Plan
            run: terraform plan

          - name: Terraform Apply
            run: terraform apply -auto-approve

          - name: Terraform Output
            if: failure()
            run: terraform output

          - name: Print Terraform Log
            if: failure()
            run: cat terraform.log